/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ChatEngine.Server;
import static com.sun.javadoc.Doclet.start;

import javax.swing.*;

import java.io.IOException;
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
import java.net.ServerSocket;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
=======

>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java

/**
 *
 * @author user
 */
public class test1 extends javax.swing.JFrame {

    /**
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
     * Creates new form test1
     */
    private  Server server;
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
    private SwingWorker<Void, String> worker;
    public test1() {
=======
     * Creates new form Server stat
     */
    private  Server server;
//    private SwingWorker<Void, String> worker;
=======
    SwingWorker<Void, Void> worker;
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
    public Serverstat() {
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
        initComponents();
    }
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
=======
   
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
        jTextArea1 = new javax.swing.JTextArea();
=======
=======
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
        stat = new javax.swing.JTextArea();
        start = new javax.swing.JButton();
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
        stop = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(211, 228, 205));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(211, 228, 205));

<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
=======
=======
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
        stat.setColumns(20);
        stat.setRows(5);
        stat.setAutoscrolls(false);
        stat.setFocusable(false);
        jScrollPane1.setViewportView(stat);
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
=======

        start.setBackground(new java.awt.Color(85, 117, 113));
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start Server");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    startActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java

        stop.setBackground(new java.awt.Color(85, 117, 113));
        stop.setForeground(new java.awt.Color(255, 255, 255));
        stop.setText("Stop Server");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    stopActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        start.setBackground(new java.awt.Color(85, 117, 113));
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start Server");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(5);
        jTextArea2.setRows(2);
        jTextArea2.setTabSize(2);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Server List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(start)
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
                        .addGap(41, 41, 41)
                        .addComponent(stop))
=======
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(stop)
                        .addGap(67, 67, 67))
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
=======
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(stop))
                .addContainerGap(100, Short.MAX_VALUE))
        );

<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 500));
=======
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
    private void startActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_startActionPerformed
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
        worker = new SwingWorker<Void, String>() {
=======
        stat.append("Server Started..");
        start.setEnabled(false);
        worker = new SwingWorker<Void, Void>() {
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
            @Override
            protected Void doInBackground() throws Exception {
                int port = 12345;
                Server server = new Server(port);
                server.start();
                return null;
            }
        };
        
        worker.execute();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
       dispose();

    }//GEN-LAST:event_stopActionPerformed
=======
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

            
    }//GEN-LAST:event_formWindowOpened

<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        stat.append("Server Started..\n");
        start.setEnabled(false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                int port = 12345;
                server = new Server(port);
                server.start();
                return null;
            }
        };

        worker.execute();
        
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {
         server.stop();
//         this.dispose();
=======
    private void stopActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
         
        this.dispose();
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
//        new Login().show();

    }                                    
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
<<<<<<< Updated upstream:Chatify-chat-app/src/GUI/test1.java
    public static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
=======
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
=======
>>>>>>> Stashed changes:Chatify-chat-app/src/GUI/Serverstat.java
    private javax.swing.JButton start;
    public static javax.swing.JTextArea stat;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
